name: C++ CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install build tools
      run: sudo apt-get install -y build-essential

    - name: Install Google Test
      run: sudo apt-get install -y libgtest-dev && cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv lib/*.a /usr/lib

    - name: Build with Make
      run: make all

    - name: Run tests
      run: ./test-MyAwesomeGame
